"""add user exp and battle share_token

Revision ID: 1f5015a5e901
Revises: 4c907ea3efc1
Create Date: 2026-08-05 06:46:05.327752

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f5015a5e901'
down_revision: str | Sequence[str] | None = '4c907ea3efc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exp')
    # ### end Alembic commands ###
