"""create abilities

Revision ID: 948a2ab9ff45
Revises: 
Create Date: 2026-08-05 06:11:37.378137

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '948a2ab9ff45'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
