"""battle status + async

Revision ID: 96b386b6ae55
Revises: ad8dc9f4b01b
Create Date: 2026-08-05 08:28:45.643058

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96b386b6ae55'
down_revision: str | Sequence[str] | None = 'ad8dc9f4b01b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('status', sa.String(length=10), server_default='done', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'status')
    # ### end Alembic commands ###
