"""economy: rank_points, daily dates, rank_delta

Revision ID: ad8dc9f4b01b
Revises: af3e16279858
Create Date: 2026-08-05 07:41:39.632067

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad8dc9f4b01b'
down_revision: str | Sequence[str] | None = 'af3e16279858'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('rank_delta_a', sa.Integer(), server_default='0', nullable=False))
    op.add_column('battles', sa.Column('rank_delta_b', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('rank_points', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('users', sa.Column('last_login_date', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('last_battle_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_battle_date')
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'rank_points')
    op.drop_column('battles', 'rank_delta_b')
    op.drop_column('battles', 'rank_delta_a')
    # ### end Alembic commands ###
