"""add user_ability enhance_level

Revision ID: af3e16279858
Revises: 465fd6caeac3
Create Date: 2026-08-05 06:57:28.665957

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af3e16279858'
down_revision: str | Sequence[str] | None = '465fd6caeac3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_abilities', sa.Column('enhance_level', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_abilities', 'enhance_level')
    # ### end Alembic commands ###
