"""remove spirit and enhance

Revision ID: b0aff016cb51
Revises: 96b386b6ae55
Create Date: 2026-08-05 14:37:58.232571

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0aff016cb51'
down_revision: str | Sequence[str] | None = '96b386b6ae55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_abilities', 'enhance_level')
    op.drop_column('users', 'spirit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spirit', sa.INTEGER(), nullable=False))
    op.add_column('user_abilities', sa.Column('enhance_level', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###
