"""baseline from models

Revision ID: cfe9e853c16d
Revises: 
Create Date: 2026-08-10 16:58:56.135244

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cfe9e853c16d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('tactic', sa.Text(), server_default='', nullable=False),
    sa.Column('understanding', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_guesses',
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('used_abilities', sa.JSON(), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('guess_history', sa.JSON(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('attempts_max', sa.Integer(), nullable=False),
    sa.Column('flipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('battle_id')
    )
    op.create_table('llm_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_traces_created_at', 'llm_traces', ['created_at'], unique=False)
    op.create_index('ix_llm_traces_operation', 'llm_traces', ['operation'], unique=False)
    op.create_index('ix_llm_traces_trace_id', 'llm_traces', ['trace_id'], unique=False)
    op.create_table('test_battle_guesses',
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('used_abilities', sa.JSON(), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('guess_history', sa.JSON(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('attempts_max', sa.Integer(), nullable=False),
    sa.Column('flipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('battle_id')
    )
    op.create_table('test_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('rank_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_users_username'), 'test_users', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('rank_points', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.String(length=10), nullable=True),
    sa.Column('last_battle_date', sa.String(length=10), nullable=True),
    sa.Column('reveal_on_miss', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('loadouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('style', sa.Text(), server_default='', nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tactic', sa.Text(), server_default='', nullable=False),
    sa.Column('style_interpretation', sa.Text(), server_default='', nullable=False),
    sa.Column('tactic_interpretation', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loadouts_user_id'), 'loadouts', ['user_id'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_created_at', 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_table('test_battles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='done', nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('rank_delta_a', sa.Integer(), nullable=False),
    sa.Column('rank_delta_b', sa.Integer(), nullable=False),
    sa.Column('loadout_a_name', sa.Text(), nullable=False),
    sa.Column('loadout_b_name', sa.Text(), nullable=False),
    sa.Column('guess_by', sa.Integer(), nullable=True),
    sa.Column('guess_state', sa.String(length=10), nullable=False),
    sa.Column('guess_hit', sa.Boolean(), nullable=True),
    sa.Column('guess_score', sa.Float(), nullable=True),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guess_by'], ['test_users.id'], ),
    sa.ForeignKeyConstraint(['user_a_id'], ['test_users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['test_users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['test_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_abilities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.String(length=64), nullable=False),
    sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ability_id')
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='done', nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('rank_delta_a', sa.Integer(), nullable=False),
    sa.Column('rank_delta_b', sa.Integer(), nullable=False),
    sa.Column('friendly', sa.Boolean(), nullable=False),
    sa.Column('loadout_a_id', sa.Integer(), nullable=True),
    sa.Column('loadout_b_id', sa.Integer(), nullable=True),
    sa.Column('guess_by', sa.Integer(), nullable=True),
    sa.Column('guess_text', sa.Text(), nullable=False),
    sa.Column('guess_state', sa.String(length=10), nullable=False),
    sa.Column('guess_hit', sa.Boolean(), nullable=True),
    sa.Column('guess_score', sa.Float(), nullable=True),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=True),
    sa.Column('share_token_b', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guess_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loadout_a_id'], ['loadouts.id'], ),
    sa.ForeignKeyConstraint(['loadout_b_id'], ['loadouts.id'], ),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_share_token'), 'battles', ['share_token'], unique=True)
    op.create_index(op.f('ix_battles_share_token_b'), 'battles', ['share_token_b'], unique=True)
    op.create_index('uq_battles_user_a_pending', 'battles', ['user_a_id'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.create_table('loadout_abilities',
    sa.Column('loadout_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['loadout_id'], ['loadouts.id'], ),
    sa.PrimaryKeyConstraint('loadout_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loadout_abilities')
    op.drop_index('uq_battles_user_a_pending', table_name='battles', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_battles_share_token_b'), table_name='battles')
    op.drop_index(op.f('ix_battles_share_token'), table_name='battles')
    op.drop_table('battles')
    op.drop_table('user_abilities')
    op.drop_table('test_battles')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_index('ix_request_logs_created_at', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_loadouts_user_id'), table_name='loadouts')
    op.drop_table('loadouts')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_users_username'), table_name='test_users')
    op.drop_table('test_users')
    op.drop_table('test_battle_guesses')
    op.drop_index('ix_llm_traces_trace_id', table_name='llm_traces')
    op.drop_index('ix_llm_traces_operation', table_name='llm_traces')
    op.drop_index('ix_llm_traces_created_at', table_name='llm_traces')
    op.drop_table('llm_traces')
    op.drop_table('battle_guesses')
    op.drop_table('abilities')
    # ### end Alembic commands ###
