"""create user_abilities

Revision ID: d6beba52bb5c
Revises: 99bcf66178b6
Create Date: 2026-08-05 06:18:55.802385

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6beba52bb5c'
down_revision: str | Sequence[str] | None = '99bcf66178b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_abilities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.String(length=64), nullable=False),
    sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_abilities')
    # ### end Alembic commands ###
