"""test_loadouts_persistent

Revision ID: db966a2d581b
Revises: cfe9e853c16d
Create Date: 2026-08-10 18:16:28.293107

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db966a2d581b'
down_revision: str | Sequence[str] | None = 'cfe9e853c16d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_loadouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('style', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['test_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_loadouts_name'), 'test_loadouts', ['name'], unique=True)
    op.create_index(op.f('ix_test_loadouts_user_id'), 'test_loadouts', ['user_id'], unique=False)
    op.create_table('test_loadout_abilities',
    sa.Column('loadout_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['loadout_id'], ['test_loadouts.id'], ),
    sa.PrimaryKeyConstraint('loadout_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_loadout_abilities')
    op.drop_index(op.f('ix_test_loadouts_user_id'), table_name='test_loadouts')
    op.drop_index(op.f('ix_test_loadouts_name'), table_name='test_loadouts')
    op.drop_table('test_loadouts')
    # ### end Alembic commands ###
