import { useEffect, useState } from "react";
import { api } from "../../api";
import { TrashIcon } from "../../components/icons";
import type { AdminLoadout, Friendship } from "./types";

type Tab = "loadouts" | "friendships";
export default function AdminRelations() {
  const [tab, setTab] = useState<Tab>("loadouts"); const [loadouts, setLoadouts] = useState<AdminLoadout[]>([]); const [friends, setFriends] = useState<Friendship[]>([]); const [err, setErr] = useState("");
  async function load() { try { if (tab === "loadouts") setLoadouts(await api<AdminLoadout[]>("/admin/loadouts")); else setFriends(await api<Friendship[]>("/admin/friendships")); } catch (e: any) { setErr(e.message); } }
  useEffect(() => { load(); }, [tab]);
  async function removeLoadout(item: AdminLoadout) { if (!window.confirm(`确认删除奇人「${item.name}」？`)) return; try { await api(`/admin/loadouts/${item.id}`, { method: "DELETE" }); await load(); } catch (e: any) { setErr(e.message); } }
  async function removeFriend(item: Friendship) { if (!window.confirm(`确认删除「${item.user ?? item.user_id}」与「${item.friend ?? item.friend_id}」的故人关系？`)) return; try { await api(`/admin/friendships/${item.user_id}/${item.friend_id}`, { method: "DELETE" }); await load(); } catch (e: any) { setErr(e.message); } }
  return <div className="admin-page"><div className="admin-toolbar"><div><span className="eyebrow">RELATION ARCHIVE</span><h2>{tab === "loadouts" ? "奇人与故人" : "故人关系"}</h2></div><div className="admin-tabs"><button className={tab === "loadouts" ? "is-active" : ""} onClick={() => setTab("loadouts")}>奇人</button><button className={tab === "friendships" ? "is-active" : ""} onClick={() => setTab("friendships")}>故人</button></div></div>{err && <p className="err">{err}</p>}{tab === "loadouts" ? <div className="tbl-list">{loadouts.map((item) => <div className="tbl-row" key={item.id}><span className="tbl-col mono">#{item.id}</span><span className="tbl-col tbl-col--main"><b>{item.name}</b><small>{item.username ?? "已离席"}</small></span><span className="tbl-col">奇术 {item.ability_count}</span><span className="tbl-col">{item.enabled ? "启用" : "停用"}</span><span className="tbl-col tbl-actions"><button className="btn btn-danger btn-icon btn-sm" onClick={() => removeLoadout(item)}><TrashIcon size={14} /></button></span></div>)}</div> : <div className="tbl-list">{friends.map((item) => <div className="tbl-row" key={`${item.user_id}-${item.friend_id}`}><span className="tbl-col mono">#{item.user_id} ↔ #{item.friend_id}</span><span className="tbl-col tbl-col--main"><b>{item.user ?? "已离席"}</b> <i>与</i> <b>{item.friend ?? "已离席"}</b></span><span className="tbl-col">{item.status}</span><span className="tbl-col tbl-actions"><button className="btn btn-danger btn-icon btn-sm" onClick={() => removeFriend(item)}><TrashIcon size={14} /></button></span></div>)}</div>}{tab === "loadouts" && loadouts.length === 0 && <div className="empty"><p>暂无奇人。</p></div>}{tab === "friendships" && friends.length === 0 && <div className="empty"><p>暂无故人关系。</p></div>}</div>;
}
